/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parkir;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paymin
 */
public class Keluar extends javax.swing.JFrame {

    /**
     * Creates new form Keluar
     */
    public Keluar() {
        initComponents();
        SetTanggal();
        SetJam();
        selectData();
    }
    
    String nol_detik = "";
    String nol_menit = "";
    String nol_jam = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jKeterangan = new javax.swing.JTextField();
        jTanggal = new javax.swing.JTextField();
        jNopol = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        jJam = new javax.swing.JTextField();
        cbJenis = new javax.swing.JComboBox<>();
        jCari1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTanggal1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jJam1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jBiaya = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabel = new javax.swing.JTable();
        jCari = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(240, 170, 27));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Parkir Keluar Selatan");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 20, 130, 10);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Mall Moklet Malang");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 30, 180, 30);

        jPanel2.setBackground(new java.awt.Color(240, 196, 75));
        jPanel2.setLayout(null);

        jKeterangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKeteranganActionPerformed(evt);
            }
        });
        jPanel2.add(jKeterangan);
        jKeterangan.setBounds(120, 170, 170, 30);

        jTanggal.setEditable(false);
        jPanel2.add(jTanggal);
        jTanggal.setBounds(120, 50, 170, 30);

        jNopol.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jNopol.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jNopol.setText("Nopol");
        jPanel2.add(jNopol);
        jNopol.setBounds(600, 50, 220, 110);

        jLabel4.setText("Keterangan");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 170, 80, 30);

        jLabel5.setText("Jam Masuk");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 90, 80, 30);

        jLabel7.setText("Jenis");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 130, 80, 30);

        jLabel9.setText("Tanggal Masuk");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 50, 100, 30);

        btnReset.setText("RESET");
        jPanel2.add(btnReset);
        btnReset.setBounds(720, 220, 100, 40);

        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel2.add(btnSimpan);
        btnSimpan.setBounds(600, 220, 100, 40);

        jJam.setEditable(false);
        jPanel2.add(jJam);
        jJam.setBounds(120, 90, 170, 30);

        cbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mobil", "Motor" }));
        jPanel2.add(cbJenis);
        cbJenis.setBounds(120, 130, 170, 30);

        jCari1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCari1ActionPerformed(evt);
            }
        });
        jPanel2.add(jCari1);
        jCari1.setBounds(70, 10, 90, 30);

        jButton2.setText("Cari");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(170, 10, 51, 30);

        jLabel3.setText("Id Parkir");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 10, 60, 30);

        jTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTotal.setText("Rp. 000,0-");
        jTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTotalActionPerformed(evt);
            }
        });
        jPanel2.add(jTotal);
        jTotal.setBounds(600, 170, 220, 30);

        jLabel10.setText("Tanggal Keluar");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(300, 50, 100, 30);

        jTanggal1.setEditable(false);
        jPanel2.add(jTanggal1);
        jTanggal1.setBounds(390, 50, 190, 30);

        jLabel6.setText("Jam Keluar");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(300, 90, 80, 30);

        jJam1.setEditable(false);
        jPanel2.add(jJam1);
        jJam1.setBounds(390, 90, 190, 30);

        jLabel8.setText("Biaya Per Hari");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(300, 130, 80, 30);

        jBiaya.setEditable(false);
        jPanel2.add(jBiaya);
        jBiaya.setBounds(390, 130, 190, 30);

        jPanel3.setBackground(new java.awt.Color(240, 208, 75));

        jTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Parkir", "Tanggal Masuk", "Jam Masuk", "Tanggal Keluar", "Jam Keluar", "Jenis", "Nopol", "Total", "Keterangan"
            }
        ));
        jScrollPane1.setViewportView(jTabel);

        jCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCariActionPerformed(evt);
            }
        });

        jButton1.setText("Cari Id Parkir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jCari, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 268, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(79, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(228, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jKeteranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKeteranganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jKeteranganActionPerformed
    
    public void SetTanggal(){
        java.util.Date skrg = new java.util.Date();
        java.text.SimpleDateFormat kal = new
        java.text.SimpleDateFormat("yyyy-MM-dd");
        jTanggal1.setText(kal.format(skrg));
    }
    public void SetJam(){
        ActionListener taskPerformer = new ActionListener(){
            public void actionPerformed(ActionEvent evt){
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                if(nilai_jam <= 9){
                    nol_jam = "0";
                }
                if(nilai_menit <= 9){
                    nol_menit = "0";
                }
                if (nilai_detik <=9){
                    nol_detik ="0";
                }
                
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                jJam1.setText(jam+":"+menit+":"+detik);;
            }
        };
        new Timer(100, taskPerformer).start();
    }
    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:

        if("".equals(jTanggal.getText()) || "".equals(jJam.getText()) || "".equals(cbJenis.getSelectedItem()) ||
            "".equals(jNopol.getText()) || "".equals(jTanggal1.getText())|| "".equals(jJam1.getText())|| "".equals(jTotal.getText())) 
        {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else {

            String SQL = "INSERT INTO parkir_keluar (tanggal_masuk,jam_masuk, jenis, nopol,keterangan, tanggal_keluar, "
                    + "jam_keluar, total)"
            + "VALUES('"+jTanggal.getText()+"','"+jJam.getText()+"','"+cbJenis.getSelectedItem()+"','" + jNopol.getText()+"','"
            + jKeterangan.getText()+"','" + jTanggal1.getText()+"','" + jJam1.getText()+"','" + jTotal.getText()+"')";
            int status = KoneksiDB.execute(SQL);
            if (status == 1){
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan","Sukses", JOptionPane.WARNING_MESSAGE);
            }
        }

    }//GEN-LAST:event_btnSimpanActionPerformed

    private void jCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCariActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String kolom[] = {"Id Parkir","Tanggal Masuk","Jam Masuk","Tanggal Keluar","Jam Keluar",
            "Jenis","Nopol","Total","Keterangan"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM parkir_keluar WHERE="+jCari.getText();
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try{
            while(rs.next()){
               String id_parkir = rs.getString(1);
               String tanggal_masuk = rs.getString(2);
               String jam_masuk = rs.getString(3);
               String jenis= rs.getString(4);
               String keterangan = rs.getString(5);
               String tanggal_keluar = rs.getString(6);
               String jam_keluar = rs.getString(7);
               String nopol = rs.getString(8);
               String total = rs.getString(9);
               String data[] = {id_parkir,tanggal_masuk,jam_masuk,tanggal_keluar, jam_keluar, 
                   jenis,nopol,total, keterangan};
               dtm.addRow(data);
            }
        } catch (SQLException ex){
            Logger.getLogger(Masuk.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTabel.setModel(dtm);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String SQL = "SELECT * FROM parkir_masuk WHERE id_parkir="+jCari1.getText();
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try{
            while(rs.next()){
                String id_parkir = rs.getString(1);
                String tanggal_masuk = rs.getString(2);
                String jam_masuk = rs.getString(3);
                String jenis= rs.getString(4);
                String nopol = rs.getString(5);
                String keterangan = rs.getString(6);
                
                jTanggal.setText(tanggal_masuk);
                jJam.setText(jam_masuk);
                cbJenis.setSelectedItem(jenis);
                jNopol.setText(nopol);
                jKeterangan.setText(keterangan);
                
                if(cbJenis.getSelectedItem() == "Motor"){
                    jBiaya.setText("6000");
                } else {
                    jBiaya.setText("10000");
                }
                
                DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
                
                try{
                    Date TanggalMasuk = df.parse(jTanggal.getText());
                    Date TanggalKeluar = df.parse(jTanggal1.getText());
                    
                    long Hari1 = TanggalMasuk.getTime();
                    long Hari2 = TanggalKeluar.getTime();
                    long diff = Hari2 - Hari1;
                    long Lama = diff/(24 * 60 * 60 *1000);
                    
                    Long String;
                    String = Lama * Long.parseLong(jBiaya.getText());
                    
                    jTotal.setText("Rp." + Long.toString(String));
                    
                } catch (ParseException e){
                    e.printStackTrace();
                }
                
                
            }
        } catch (SQLException ex){
            Logger.getLogger(Masuk.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCari1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCari1ActionPerformed

    private void jTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Keluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Keluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Keluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Keluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Keluar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbJenis;
    private javax.swing.JTextField jBiaya;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jCari;
    private javax.swing.JTextField jCari1;
    private javax.swing.JTextField jJam;
    private javax.swing.JTextField jJam1;
    private javax.swing.JTextField jKeterangan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNopol;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabel;
    private javax.swing.JTextField jTanggal;
    private javax.swing.JTextField jTanggal1;
    private javax.swing.JTextField jTotal;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"Id Parkir","Tanggal Masuk","Jam Masuk","Tanggal Keluar","Jam Keluar",
            "Jenis","Nopol","Total","Keterangan"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM parkir_keluar";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try{
            while(rs.next()){
               String id_parkir = rs.getString(1);
               String tanggal_masuk = rs.getString(2);
               String jam_masuk = rs.getString(3);
               String jenis= rs.getString(4);
               String keterangan = rs.getString(5);
               String tanggal_keluar = rs.getString(6);
               String jam_keluar = rs.getString(7);
               String nopol = rs.getString(8);
               String total = rs.getString(9);
               String data[] = {id_parkir,tanggal_masuk,jam_masuk,tanggal_keluar, jam_keluar, 
                   jenis,nopol,total, keterangan};
               dtm.addRow(data);
            }
        } catch (SQLException ex){
            Logger.getLogger(Masuk.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTabel.setModel(dtm); //To change body of generated methods, choose Tools | Templates.
    }
}
