/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parkir;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paymin
 */
public class Masuk extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Masuk() {
        initComponents();
        SetTanggal();
        SetJam();
        selectData();
    }
    
    String nol_detik = "";
    String nol_menit = "";
    String nol_jam = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jKeterangan = new javax.swing.JTextField();
        jTanggal = new javax.swing.JTextField();
        jNopol = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        jJam = new javax.swing.JTextField();
        cbJenis = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabel = new javax.swing.JTable();
        jCari = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(240, 170, 27));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Parkir Masuk Utara");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 20, 130, 10);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Mall Moklet Malang");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 30, 180, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 700, 80);

        jPanel2.setBackground(new java.awt.Color(240, 196, 75));
        jPanel2.setLayout(null);

        jKeterangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKeteranganActionPerformed(evt);
            }
        });
        jPanel2.add(jKeterangan);
        jKeterangan.setBounds(120, 160, 200, 30);

        jTanggal.setEditable(false);
        jPanel2.add(jTanggal);
        jTanggal.setBounds(120, 40, 200, 30);

        jNopol.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jNopol.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jNopol.setText("Nopol");
        jPanel2.add(jNopol);
        jNopol.setBounds(340, 40, 230, 150);

        jLabel4.setText("Keterangan");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 160, 80, 30);

        jLabel5.setText("Jam Masuk");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 80, 80, 30);

        jLabel7.setText("Jenis");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 120, 80, 30);

        jLabel9.setText("Tanggal Masuk");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 40, 100, 30);

        btnReset.setText("RESET");
        jPanel2.add(btnReset);
        btnReset.setBounds(590, 90, 100, 40);

        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel2.add(btnSimpan);
        btnSimpan.setBounds(590, 40, 100, 40);

        jJam.setEditable(false);
        jPanel2.add(jJam);
        jJam.setBounds(120, 80, 200, 30);

        cbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mobil", "Motor" }));
        jPanel2.add(cbJenis);
        cbJenis.setBounds(120, 120, 200, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 60, 700, 220);

        jPanel3.setBackground(new java.awt.Color(240, 208, 75));

        jTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id Parkir", "Tanggal Masuk", "Jam Masuk", "Jenis", "Nopol", "Keterangan"
            }
        ));
        jScrollPane1.setViewportView(jTabel);

        jCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCariActionPerformed(evt);
            }
        });

        jButton1.setText("Cari Id Parkir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jCari, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 280, 700, 250);

        setBounds(0, 0, 720, 566);
    }// </editor-fold>//GEN-END:initComponents

    private void jKeteranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKeteranganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jKeteranganActionPerformed

    private void jCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCariActionPerformed

    public void SetTanggal(){
        java.util.Date skrg = new java.util.Date();
        java.text.SimpleDateFormat kal = new
        java.text.SimpleDateFormat("yyyy-MM-dd");
        jTanggal.setText(kal.format(skrg));
    }
    public void SetJam(){
        ActionListener taskPerformer = new ActionListener(){
            public void actionPerformed(ActionEvent evt){
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                if(nilai_jam <= 9){
                    nol_jam = "0";
                }
                if(nilai_menit <= 9){
                    nol_menit = "0";
                }
                if (nilai_detik <=9){
                    nol_detik ="0";
                }
                
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                jJam.setText(jam+":"+menit+":"+detik);;
            }
        };
        new Timer(100, taskPerformer).start();
    }
    
    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        
        if("".equals(jTanggal.getText()) || "".equals(jJam.getText()) || "".equals(cbJenis.getSelectedItem()) ||
                "".equals(jNopol.getText())) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
                      
            String SQL = "INSERT INTO parkir_masuk (tanggal_masuk,jam_masuk, jenis, nopol,keterangan)" 
                    + "VALUES('"+jTanggal.getText()+"','"+jJam.getText()+"','"+cbJenis.getSelectedItem()+"','" + jNopol.getText()+"','"
                    + jKeterangan.getText()+"')";
            int status = KoneksiDB.execute(SQL);
            if (status == 1){
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan","Sukses", JOptionPane.WARNING_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String kolom[] = {"Id Parkir","Tanggal Masuk","Jam Masuk","Jenis","Nopol","Keterangan"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM parkir_masuk WHERE id_parkir="+jCari.getText();
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try{
            while(rs.next()){
               String id_parkir = rs.getString(1);
               String tanggal_masuk = rs.getString(2);
               String jam_masuk = rs.getString(3);
               String jenis= rs.getString(4);
               String nopol = rs.getString(5);
               String keterangan = rs.getString(6);
               String data[] = {id_parkir,tanggal_masuk,jam_masuk,jenis,nopol,keterangan};
               dtm.addRow(data);
            }
        } catch (SQLException ex){
            Logger.getLogger(Masuk.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTabel.setModel(dtm);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Masuk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbJenis;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jCari;
    private javax.swing.JTextField jJam;
    private javax.swing.JTextField jKeterangan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JTextField jNopol;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabel;
    private javax.swing.JTextField jTanggal;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"Id Parkir","Tanggal Masuk","Jam Masuk","Jenis","Nopol","Keterangan"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM parkir_masuk";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try{
            while(rs.next()){
               String id_parkir = rs.getString(1);
               String tanggal_masuk = rs.getString(2);
               String jam_masuk = rs.getString(3);
               String jenis= rs.getString(4);
               String nopol = rs.getString(5);
               String keterangan = rs.getString(6);
               String data[] = {id_parkir,tanggal_masuk,jam_masuk,jenis,nopol,keterangan};
               dtm.addRow(data);
            }
        } catch (SQLException ex){
            Logger.getLogger(Masuk.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTabel.setModel(dtm); //To change body of generated methods, choose Tools | Templates.
    }
}
